import Head from 'next/head';
import Image from 'next/image';

import usePromise from '../lib/hooks/usePromise';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [result, error, isLoading] = usePromise(() =>
    fetch(
      `https://api.coingecko.com/api/v3/simple/price?ids=rocket-pool&vs_currencies=eth%2Cusd`
    ).then(r => r.json())
  );

  let ethRatio, usdRatio;

  if (result && !isLoading) {
    ethRatio = result['rocket-pool'].eth;
    usdRatio = result['rocket-pool'].usd;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;800&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main}>
        <h1
          className={styles.title}
          style={{ fontWeight: 'bold', fontSize: 36 }}
        >
          ROCKET<span style={{ color: '#F9DE1A' }}>POOL</span>
        </h1>
        <h2
          style={{
            marginTop: 4,
            fontSize: 32,
          }}
        >
          RATIOGANG
        </h2>

        <div style={{ marginBottom: 32 }}>
          <img src="/exhaust.svg" width={50} height={100} />
          <img src="/rocketpooliconwithexhaust.svg" height={100} />
        </div>

        <div style={{ display: 'flex' }}>
          <div
            style={{
              backgroundColor: 'rgba(255,255,255,0.15)',
              color: 'white',
              fontWeight: 400,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
              width: 160,
              borderTopLeftRadius: 5,
              borderBottomLeftRadius: 5,
              padding: 16,
              borderWidth: 1,
              borderColor: 'white',
              borderStyle: 'solid',
            }}
          >
            {!isLoading && result ? (
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                }}
              >
                <span style={{ fontSize: 20, marginRight: 4 }}>Ξ</span>
                <span style={{ fontSize: 18 }}>{ethRatio}</span>
              </div>
            ) : null}
          </div>
          <div
            style={{
              backgroundColor: 'rgba(255,255,255,0.15)',
              borderColor: 'white',
              borderTopWidth: 1,
              borderRightWidth: 1,
              borderBottomWidth: 1,
              borderLeftWidth: 0,
              borderStyle: 'solid',
              color: 'white',
              fontWeight: 400,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
              width: 160,
              borderTopRightRadius: 5,
              borderBottomRightRadius: 5,
              padding: 16,
            }}
          >
            {!isLoading && result ? (
              <div
                style={{
                  display: 'flex',
                  justifyContent: 'center',
                  alignItems: 'center',
                }}
              >
                <span style={{ fontSize: 22, marginRight: 4 }}>$</span>
                <span style={{ fontSize: 20 }}>
                  {Number(usdRatio).toFixed(2)}
                </span>
              </div>
            ) : null}
          </div>
        </div>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
